version: '3.8'

services:
  db:
    image: postgres:14
    container_name: expenses-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - expenses_data:/var/lib/postgresql/data
    networks:
      - app-network

  flyway:
    image: flyway/flyway:10.20.0
    container_name: flyway
    command: migrate -url=jdbc:postgresql://db:5432/expenses -user=user -password=password
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network

  backend:
    build:
      context: server
    container_name: expenses-server
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  expenses_data:

networks:
  app-network:
    driver: bridge
